### ISSUE TITLE
Breaks with 7.0.0-beta.3

### ISSUE THREAD

**Issue by hlehmann** [akameco/babel-plugin-react-intl-auto#12]
I just past to the last beta and I get the following error:
```
Module build failed: TypeError: Cannot read property 'imports' of undefined
    at isImportLocalName (node_modules/babel-plugin-react-intl-auto/lib/index.js:58:40)
    at isValidate (node_modules/babel-plugin-react-intl-auto/lib/index.js:109:8)
    at PluginPass.CallExpression (node_modules/babel-plugin-react-intl-auto/lib/index.js:12:14)
```
Any idea on this ?

**Comment by akameco** [comment]
Thank you for your issue @hlehmann .
Sorry about that.
I have not made babel7 correspondence yet.
I will work on it as soon as `babel-plugin-tester` supports babel 7.

**Comment by hlehmann** [comment]
@akameco any update on this ?

**Comment by akameco** [comment]
@hlehmann 
I publish new version👍
Support babel7.
Please install the latest version.

**Comment by hlehmann** [comment]
Works great thanks
